# @package _global_
module:
  _target_: emg2qwerty.lightning_new.ACModule
  in_features: 528  # freq * channels = (n_fft // 2 + 1) * 16
  mlp_features: [384]
  num_layers: 4
  kernel_width: 32
  num_heads: 4

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 600  # 300ms windows for 2kHz EMG
  padding: [0, 0]  # 
  test_window_length: 600
  #stride: 60 # No overlap