# @package _global_
module:
  _target_: emg2qwerty.lightning.ConformerCTCModule
  in_features: 528  # freq * channels = (n_fft // 2 + 1) * 16
  mlp_features: [384]
  block_channels: [24, 24, 24, 24]
  kernel_width: [17, 17, 17, 17]  # 

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 600  # 4 sec windows for 2kHz EMG
  padding: [0, 0]  # 900ms past context, 100ms future context
  test_window_length: 600
