# @package _global_
module:
  _target_: emg2qwerty.lightning.LSTMModule
  in_features: 528  # freq * channels = (n_fft // 2 + 1) * 16
  mlp_features: [384]
  hidden_features: 128
  num_layers: 8


datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 600  # 300 ms windows for 2kHz EMG
  padding: [0, 0]  # No extra padding 
  test_window_length: 600 
  
