# @package _global_
module:
  _target_: emg2qwerty.lightning.SandwichLSTM_TDSModule
  in_features: 528  # freq * channels = (n_fft // 2 + 1) * 16
  mlp_features: [384]
  block_channels: [24, 24, 24, 24]
  hidden_features: 128
  num_layers: 4
  kernel_width: 9  

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 600  # 300 ms windows for 2kHz EMG
  padding: [0, 0]  # No extra padding 
  test_window_length: 600 
  
