# @package _global_
module:
  _target_: emg2qwerty.lightning.WaveTDSConvCTCModule
  in_features: 16  # channels = 16
  mlp_features: [384]
  block_channels: [24, 24, 24, 24]
  kernel_width: 32  # Total temporal receptive field of 125 samples given 4 layers

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 4000 #600  # 300 ms windows for 2kHz EMG
  padding: [900, 100] #[0, 0]  # No extra padding 
