# @package _global_
module:
  _target_: emg2qwerty.lightning.TDS_TC_CTCModule
  in_features: 528  # freq * channels = (n_fft // 2 + 1) * 16
  mlp_features: [384]
  block_channels: [24, 24]
  kernel_width_tds: 32
  subsample_features: 512
  num_layers: 2
  kernel_width_tc: 5 
  num_heads: 4
  max_len: 4096

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
  test_window_length: 8000
