# @package _global_
low_pass:
  _target_: emg2qwerty.transforms.LowPassFilter
  cutoff: 450
  order: 2

to_tensor:
  _target_: emg2qwerty.transforms.ToTensor
  fields: [emg_left, emg_right]

band_rotation:
  _target_: emg2qwerty.transforms.ForEach  # i.i.d rotation offset for each band
  transform:
    _target_: emg2qwerty.transforms.RandomBandRotation
    offsets: [-1, 0, 1]

temporal_jitter:
  _target_: emg2qwerty.transforms.TemporalAlignmentJitter
  max_offset: 30  # Max 15ms jitter for 2kHz EMG


transforms:
  train:
    - ${to_tensor}
    #- ${low_pass}
    - ${band_rotation}
    - ${temporal_jitter}

  val:
    - ${to_tensor}
    #- ${low_pass}

  test: ${transforms.val}
